/*	Program:	json2tree2hist.js
	Author:		Viktor Zerkin, V.Zerkin@gmail.com
	Last modified:	2024-01-26
	Distribution:	2024-02-01
	Property of:	Viktor Zerkin
	Project:	Multi-Platform Nuclear Reaction Databases           
	Usage:		with proper acknolegement to the author
	Distribution:	restricted while the project has not been finished  
	Modifications:	can be done with permission of the author           
	Note:		this is non-commercial software and it comes with   
			NO WARRANTY                                         
*/
var nfiles=0;function outmylog(a,b,c){if(c==0){outmyHist(a)}else{outmyVers(b)}outEndJsonEdt()}function outmyHist(b){var a,f,e,c,d;document.write("Operation log.<br>");begHist();for(a=0;a<b.length;a++){c=b[a];ts=c.ts;act=c.act;outHist(a,b.length,ts,act);nfiles++}endHist()}function outmyVers(b){var a,f,e,c,d;document.write("Versions of current JSON file.<br>");begVers();for(a=b.length-1;a>=0;a--){c=b[a];ts=c.ts;act=c.act;f=c.jsonTxt;if(f!=null){d="json-length="+f.length}console.log("["+a+"/"+b.length+"]---ts:"+ts+" act:["+act+"] "+d);outVers(a,b.length,ts,act,f);nfiles++}endVers()}function restoreVersion(a){window.opener.restoreJsonLogVersion(a)}function clearVersions(){window.opener.clearJsonLogVersion()}function begVers(){document.writeln('<table border=1 style="background-color:white;">');document.write("<td align=right>#</td>");document.write("<td><i>Time</i></td>");document.write("<td align=right><i>JSON:Len</i></td>");document.write("<td>Version</td>");document.write("<td><i>Action</i></td>");document.write("<td><i>Node</i></td>");document.write("<tr>")}function endVers(){document.writeln("</table>");var a='<a href="#" onclick="javascript:clearVersions();return false;" title="Clear versions log">[Clear History]</a>';document.writeln(a)}function outVers(e,a,h,d,j,k){var g="",k="",b,f="",i="",c=h;b=h.indexOf(",");if(b>=0){c=h.substring(b+1)}b=d.indexOf(":");if(b>=0){k=d.substring(b+1);g=d.substring(0,b)}if(j!=null){f=j.length}i='<a href="#" onclick="javascript:restoreVersion('+e+',event);return false;" title="Continue editing starting from thise version">['+e+"]<small>&nearr;</small></a>";document.write("<tr>");document.write("<td align=right>"+e+"</td>");document.write("<td>"+c+"</td>");document.write("<td align=right>"+f+"</td>");document.write("<td>&nbsp; "+i+"</td>");document.write("<td>"+g+"</td>");document.write("<td>"+k+"</td>");document.write("</tr>")}function begHist(){document.writeln('<table border=1 style="background-color:white;">');document.write("<td align=right>#</td>");document.write("<td><i>Time</i></td>");document.write("<td align=right><i>JSON:Len</i></td>");document.write("<td><i>Action</i></td>");document.write("<td><i>Node</i></td>");document.write("<tr>")}function endHist(){document.writeln("</table>")}function outHist(e,a,h,d,j){var g="",j="",b,f="",i="",c=h;b=d.indexOf(":");if(b>=0){j=d.substring(b+1);g=d.substring(0,b)}b=j.indexOf(" json-length=");if(b>=0){f=j.substring(b+1+12);j=j.substring(0,b)}b=h.indexOf(",");if(b>=0){c=h.substring(b+1)}document.write("<tr>");document.write("<td align=right>"+e+"</td>");document.write("<td>"+c+"</td>");document.write("<td align=right>"+f+"</td>");document.write("<td>"+g+"</td>");document.write("<td>"+j+"</td>");document.write("</tr>")};